require 'yaml'
disks                   = ENV['DISKS_LOCATION'] || 'disks/'  
VAGRANTFILE_API_VERSION = '2'
REQUIRED_PLUGINS        = %w(vagrant-hostmanager)
SUGGESTED_PLUGINS       = %w(vagrant-sshfs landrush)
errors                  = []
servers                 = YAML.load_file('servers.yaml')
box_name                = 'centos/7'


def message(name)
  "#{name} plugin is not installed, run `vagrant plugin install #{name}` to install it."
end

SUGGESTED_PLUGINS.each { |plugin| print("note: " + message(plugin) + "\n") unless Vagrant.has_plugin?(plugin) }

# Validate and collect error message if plugin is not installed
REQUIRED_PLUGINS.each { |plugin| errors << message(plugin) unless Vagrant.has_plugin?(plugin) }
unless errors.empty?
  msg = errors.size > 1 ? "Errors: \n* #{errors.join("\n* ")}" : "Error: #{errors.first}"
  fail Vagrant::Errors::VagrantError.new, msg
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.registration.skip = true
  config.registration.unregister_on_halt = false
	
  if Vagrant.has_plugin?('landrush')
    config.landrush.enabled = true
    config.landrush.tld = 'example.com'
    config.landrush.guest_redirect_dns = false
  end

  # Suppress the default sync in both CentOS base and CentOS Atomic Host
  #  config.vm.synced_folder '.', '/vagrant', disabled: true
  #  config.vm.synced_folder '.', '/home/vagrant/sync', disabled: true

  servers.each do |servers|
    config.vm.define servers["alias"] do |serv|
	serv.vm.box = box_name
	serv.vm.network :private_network, ip: servers["ip"]
	serv.hostmanager.aliases = servers["alias"]
        serv.vm.hostname = servers["name"]
	host= servers["name"]
	serv.vm.provider :virtualbox do |domain|
		if servers["disks"]		
			servers["disks"].each do |disk|  
                		selected_disk = disks + disk["disk_name"]
				unless File.exist?(selected_disk)
       						domain.customize ['createhd', '--filename', selected_disk, '--size', disk["disk_size"]]
        			end
      				domain.customize ['storageattach', :id, '--storagectl', 'IDE', '--port',1, '--device', 0,
					  '--type','hdd', '--medium', selected_disk]
                                
			end
		end
   		domain.memory = servers["memory"]
	        domain.cpus   = servers["cpu"]

		#shared folders using sshfs
		if servers["sync"]
			servers["sync"].each do |sync| 
				serv.vm.synced_folder sync["source"], sync["target"], type: sync["sync_type"]
			end
		end

		#ansible provisioning 
		if servers["ansible"]
			servers["ansible"].each do |ans|   
				 serv.vm.provision :ansible_local do |ansible|
					ansible.verbose           = ans["verbose"]
				        ansible.install           = ans["install"]
			    	        ansible.limit             = ans["group"]
				        ansible.provisioning_path = ans["path"]
				        ansible.playbook          = ans["playbook"]
				        ansible.inventory_path    = ans["inventory"]
		                 end 	 
				
			end	
		end    
		
        end 
    end
	
  end

end


